apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
       containers:
           - name: api
             image: saranee/simple_blog_api_ts-master
             ports:
                 - containerPort: 3000
             env: 
                - name: POSTGRES_HOST
                  value: postgres-cluster-ip-service
                - name: POSTGRES_PORT
                  value: "5432"
                - name: POSTGRES_USERNAME
                  value: postgres
                - name: POSTGRES_DB
                  value: simple_blog_api
                - name: POSTGRES_PASSWORD
                  valueFrom:
                      secretKeyRef:
                        name: pgpassword
                        key: POSTGRES_PASSWORD               
             resources:
                 limits:
                     memory: "256Mi"
                     cpu: "500m"
        
